blog/urls.py
from django.urls import path

from . import views
app_name = 'blog'
urlpatterns = [
     path('', views.home_page, name='home_page'),
]

my_site/urls.py
from django.urls import include, path 
from django.contrib import admin

urlpatterns = [ 
     path('', include('blog.urls')), 
     path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render

def home_page(request):

    if request.method == 'POST':
        comment = request.POST.get('comment')
        user = request.POST.get("username")

        print(comment * 10)
        return render(request, 'blog/home_page.html', {'comment': comment, 'username': user})

    return render(request, 'blog/home_page.html')

blog/templates/blog/home_page.html
<!DOCTYPE html>
<html>
<head>
	<title>Welcome to Sage's Blog</title>
</head>
<body>
 <!-- Site Header -->
<h1>Hi. I am Ruby. Welcome to my blog</h1>
<img src="http://tse4.mm.bing.net/th?id=OIP.tBO60pF8llDwImljbe2udgHaE8&pid=Api">
<!-- Blog Post -->
 <h2>My First Blog Post</h2>
  <p>Here is my first blog post. One day at the mall....</p>

<!-- Like And Comment -->
 <button>Like</button>
 <h2>Leave a Comment</h2>
 <form action="{% url 'blog:home_page' %}" method="POST">
{% csrf_token %}
<input type="text" placeholder="Please Enter Your Comment"></text area><br>
<input type="submit" value="Post me!">
</form>

<h2>Comments</h2>
 User {{username}} says: {{comment}}
</body>
</html>